[package]
name = "lean-homotopy-theory"
version = "0.1"
lean_version = "3.4.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "e429aacecf0a003eb1d36e08b5950ac2b269e2c7"}
lean-category-theory-pr = {git = "https://github.com/semorrison/lean-category-theory-pr", rev = "56f9cc9474a12665f013112c54aff6198447a395"}
